In [21]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.DataFrame(pd.read_excel('Finance.xlsx'))
type(data)

pandas.core.frame.DataFrame

In [3]:
data

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow
0,Microsoft,2022,198270,72738,364840,198298,89035
1,Microsoft,2023,211915,72361,411976,205753,87582
2,Microsoft,2024,245122,88136,512163,243686,118548
3,Tesla,2022,81462,12556,82338,82338,14724
4,Tesla,2023,96773,14974,106618,43009,13256
5,Tesla,2024,97690,7153,122070,48390,14923
6,Apple,2022,394328,99803,352755,302083,35929
7,Apple,2023,383285,96995,352583,290437,24977
8,Apple,2024,391035,93736,364980,308030,30737

## Rolling Data

In [9]:
rolling_data = pd.DataFrame()
rolling_data[['Rolling Revenue','Rolling Net Income', 'Rolling total Assets', 'Rolling Liabilities', 'Rolling Cash Flow']] = data.groupby(['Company','Year'])[['Total Revenue', 'Net Income', ' Total Assets','Total Liabilities', 'Cash Flow']].rolling(window = 3,min_periods =1).mean()

In [10]:
rolling_data

                  Rolling Revenue  Rolling Net Income  Rolling total Assets  \
Company   Year
Apple     2022 6         394328.0             99803.0              352755.0
          2023 7         383285.0             96995.0              352583.0
          2024 8         391035.0             93736.0              364980.0
Microsoft 2022 0         198270.0             72738.0              364840.0
          2023 1         211915.0             72361.0              411976.0
          2024 2         245122.0             88136.0              512163.0
Tesla     2022 3          81462.0             12556.0               82338.0
          2023 4          96773.0             14974.0              106618.0
          2024 5          97690.0              7153.0              122070.0

                  Rolling Liabilities  Rolling Cash Flow
Company   Year
Apple     2022 6             302083.0            35929.0
          2023 7             290437.0            24977.0
          2024 8             308030.0            30737.0
Microsoft 2022 0             198298.0            89035.0
          2023 1             205753.0            87582.0
          2024 2             243686.0           118548.0
Tesla     2022 3              82338.0            14724.0
          2023 4              43009.0            13256.0
          2024 5              48390.0            14923.0

## Cummulative Growth

In [11]:
cummulative = pd.DataFrame()
cummulative[['Cummulative Revenue','Cummulative Assets']] = data.groupby(['Company','Year'])[['Total Revenue',' Total Assets']].expanding().sum()
cummulative

                  Cummulative Revenue  Cummulative Assets
Company   Year
Apple     2022 6             394328.0            352755.0
          2023 7             383285.0            352583.0
          2024 8             391035.0            364980.0
Microsoft 2022 0             198270.0            364840.0
          2023 1             211915.0            411976.0
          2024 2             245122.0            512163.0
Tesla     2022 3              81462.0             82338.0
          2023 4              96773.0            106618.0
          2024 5              97690.0            122070.0

## Pivot Table

In [14]:
data.pivot_table(values = ['Total Revenue','Net Income'], index = 'Year', columns = 'Company', aggfunc = 'sum')

        Net Income                  Total Revenue
Company      Apple Microsoft  Tesla         Apple Microsoft  Tesla
Year
2022         99803     72738  12556        394328    198270  81462
2023         96995     72361  14974        383285    211915  96773
2024         93736     88136   7153        391035    245122  97690

## Percentage Change

In [20]:

data[['Total Revenue %', 'Net Income %', 'Total Assets %', 'Total Liabilities %', 'Cash Flow%']] = data.groupby('Company')[['Total Revenue', 'Net Income', ' Total Assets', 'Total Liabilities', 'Cash Flow']].pct_change() * 100
data

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow,Total Revenue %,Net Income %,Total Assets %,Total Liabilities %,Cash Flow%
0,Microsoft,2022,198270,72738,364840,198298,89035,NaN,NaN,NaN,NaN,NaN
1,Microsoft,2023,211915,72361,411976,205753,87582,6.882030,-0.518299,12.919636,3.759493,-1.631942
2,Microsoft,2024,245122,88136,512163,243686,118548,15.669962,21.800417,24.318650,18.436183,35.356580
3,Tesla,2022,81462,12556,82338,82338,14724,NaN,NaN,NaN,NaN,NaN
4,Tesla,2023,96773,14974,106618,43009,13256,18.795267,19.257725,29.488207,-47.765309,-9.970117
5,Tesla,2024,97690,7153,122070,48390,14923,0.947578,-52.230533,14.492862,12.511335,12.575438
6,Apple,2022,394328,99803,352755,302083,35929,NaN,NaN,NaN,NaN,NaN
7,Apple,2023,383285,96995,352583,290437,24977,-2.800461,-2.813543,-0.048759,-3.855232,-30.482340
8,Apple,2024,391035,93736,364980,308030,30737,2.021994,-3.359967,3.516052,6.057424,23.061216