# Financial Chatbot

## 📌 Overview
This chatbot provides financial insights based on predefined queries.

## 🚀 How to Run
1. Install Jupyter Notebook and pandas library.
2. open `chatbot.ipynb` in Jupyter Notebook
3. Follow the on-screen prompts.

## 📉 Limitations
- Only supports predefined financial metrics.
- Data is hardcoded for Microsoft only.
- Doesn't support natural language input.

In [67]:
import pandas as pd

In [2]:
df = pd.DataFrame(pd.read_excel('Finance.xlsx'))

In [3]:
df

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow
0,Microsoft,2022,198270,72738,364840,198298,89035
1,Microsoft,2023,211915,72361,411976,205753,87582
2,Microsoft,2024,245122,88136,512163,243686,118548
3,Tesla,2022,81462,12556,82338,82338,14724
4,Tesla,2023,96773,14974,106618,43009,13256
5,Tesla,2024,97690,7153,122070,48390,14923
6,Apple,2022,394328,99803,352755,302083,35929
7,Apple,2023,383285,96995,352583,290437,24977
8,Apple,2024,391035,93736,364980,308030,30737

## ChatBot for Microsoft

In [5]:
microsoft_df = df[df['Company'] == 'Microsoft'].sort_values(by = 'Year')
microsoft_df

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow
0,Microsoft,2022,198270,72738,364840,198298,89035
1,Microsoft,2023,211915,72361,411976,205753,87582
2,Microsoft,2024,245122,88136,512163,243686,118548

In [71]:
microsoft_df.columns = df.columns.str.strip()

In [69]:
def assets(year):
    result = microsoft_df[microsoft_df['Year'] == year]
    if not result.empty:
        return f"Total Assets in {year}: ${result['Total Assets'].values[0]:,.2f}"
    return "Year not found."

def liabilities(year):
    result = microsoft_df[microsoft_df['Year'] == year]
    if not result.empty:
        return f"Total Liabilities in {year}: ${result['Total Liabilities'].values[0]:,.2f}"
    return "Year not found."

def trend(parameter):
    rolling_mean = microsoft_df[parameter].rolling(window=3, min_periods=1).mean()
    if rolling_mean.iloc[-1] > rolling_mean.iloc[-2]:
        return "Increasing"
    else:
        return "Decreasing"

def percent_growth(parameter):
    percentage_growth = ((microsoft_df[parameter].pct_change()) * 100).iloc[-1]
    return f"{parameter} percentage growth: {percentage_growth:.2f}%"

In [73]:

def assets(year):
    result = microsoft_df[microsoft_df['Year'] == year]
    if not result.empty:
        return f"Total Assets in {year}: ${result['Total Assets'].values[0]:,.2f}"
    return "Year not found."


def liabilities(year):
    result = microsoft_df[microsoft_df['Year'] == year]
    if not result.empty:
        return f"Total Liabilities in {year}: ${result['Total Liabilities'].values[0]:,.2f}"
    return "Year not found."


def trend(parameter):
    parameter = parameter.strip()  
    if parameter not in microsoft_df.columns:
        return "Invalid parameter."
    
    rolling_mean = microsoft_df[parameter].rolling(window=3, min_periods=1).mean()
    return "Increasing" if rolling_mean.iloc[-1] > rolling_mean.iloc[-2] else "Decreasing"


def percent_growth(parameter):
    parameter = parameter.strip()  
    if parameter not in microsoft_df.columns:
        return "Invalid parameter."
    
    percentage_growth = ((microsoft_df[parameter].pct_change()) * 100).iloc[-1]
    return f"{parameter} percentage growth: {percentage_growth:.2f}%"


while True:
    print("\nChoose an option:")
    print("1. Get Total Assets")
    print("2. Get Total Liabilities")
    print("3. Check Trend (Increasing/Decreasing)")
    print("4. Check Percentage Growth")
    print("5. Exit")
    
    choice = input("Enter your choice (1-5): ")
    
    if choice == '1':
        year = int(input("Enter year (e.g., 2020): "))
        print(assets(year))
    
    elif choice == '2':
        year = int(input("Enter year (e.g., 2020): "))
        print(liabilities(year))
    
    elif choice == '3':
        param = input("Enter financial parameter (Total Assets, Total Liabilities, Cash Flow, Net Income): ")
        print(f"{param} Trend: {trend(param)}")
    
    elif choice == '4':
        param = input("Enter financial parameter (Total Assets, Total Liabilities, Cash Flow, Net Income): ")
        print(percent_growth(param))
    
    elif choice == '5':
        print("Exiting the program.")
        break
    
    else:
        print("Invalid choice. Please enter a number between 1 and 5.")

Choose an option:
1. Get Total Assets
2. Get Total Liabilities
3. Check Trend (Increasing/Decreasing)
4. Check Percentage Growth
5. Exit

Enter your choice (1-5):  1
Enter year (e.g., 2020):  2023

Total Assets in 2023: $411,976.00

Choose an option:
1. Get Total Assets
2. Get Total Liabilities
3. Check Trend (Increasing/Decreasing)
4. Check Percentage Growth
5. Exit

Enter your choice (1-5):  2
Enter year (e.g., 2020):  2022

Total Liabilities in 2022: $198,298.00

Choose an option:
1. Get Total Assets
2. Get Total Liabilities
3. Check Trend (Increasing/Decreasing)
4. Check Percentage Growth
5. Exit

Enter your choice (1-5):  3
Enter financial parameter (Total Assets, Total Liabilities, Cash Flow, Net Income):  cash Flow

cash Flow Trend: Invalid parameter.

Choose an option:
1. Get Total Assets
2. Get Total Liabilities
3. Check Trend (Increasing/Decreasing)
4. Check Percentage Growth
5. Exit

Enter your choice (1-5):  3
Enter financial parameter (Total Assets, Total Liabilities, Cash Flow, Net Income):  Cash Flow

Cash Flow Trend: Increasing

Choose an option:
1. Get Total Assets
2. Get Total Liabilities
3. Check Trend (Increasing/Decreasing)
4. Check Percentage Growth
5. Exit

Enter your choice (1-5):  4
Enter financial parameter (Total Assets, Total Liabilities, Cash Flow, Net Income):  Net Income

Net Income percentage growth: 21.80%

Choose an option:
1. Get Total Assets
2. Get Total Liabilities
3. Check Trend (Increasing/Decreasing)
4. Check Percentage Growth
5. Exit

Enter your choice (1-5):  5

Exiting the program.